import { generateKeyPairSync } from 'node:crypto';
import { mkdir, writeFile, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const toolRoot = path.resolve(here, '..');
const repoRoot = path.resolve(toolRoot, '..', '..');
const keysDirectory = path.join(toolRoot, '.keys');
const privatePath = path.join(keysDirectory, 'private-key.pem');
const publicPath = path.join(keysDirectory, 'public-key.pem');
const appPublicKeyPath = path.join(repoRoot, 'electron-app', 'main', 'license-public-key.ts');
const force = process.argv.includes('--force');

await mkdir(keysDirectory, { recursive: true });
if (!force) {
  try {
    await access(privatePath);
    throw new Error('A private key already exists. Use npm run keys:generate -- --force only when intentionally replacing the licensing key.');
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
}

const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const privatePem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const publicPem = publicKey.export({ type: 'spki', format: 'pem' });

await writeFile(privatePath, privatePem, { mode: 0o600 });
await writeFile(publicPath, publicPem, 'utf8');
await writeFile(
  appPublicKeyPath,
  `// Generated by developer-tools/license-generator. Never place the private key in the application.\nexport const LICENSE_PUBLIC_KEY_PEM = \`${publicPem.trim()}\`;\n`,
  'utf8',
);

console.log(`Private key: ${privatePath}`);
console.log(`Public key:  ${publicPath}`);
console.log(`Application verifier updated: ${appPublicKeyPath}`);
console.log('Keep .keys/private-key.pem secret and outside release packages. Rebuild/restart the app after changing keys.');
