// Generated by developer-tools/license-generator. Never place the private key in the application.
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAT79Z4E82L+s+SysJPqis52I5O1JpEgtAEb71sD9/t98=
-----END PUBLIC KEY-----`;
