const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  employee: {
    list: (filters) => ipcRenderer.invoke('employee.list', filters),
    get: (id) => ipcRenderer.invoke('employee.get', id),
    create: (payload) => ipcRenderer.invoke('employee.create', payload),
    update: (id, payload) => ipcRenderer.invoke('employee.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('employee.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('employee.delete', id),
  },
  attendance: {
    list: (filters) => ipcRenderer.invoke('attendance.list', filters),
    get: (id) => ipcRenderer.invoke('attendance.get', id),
    summary: (filters) => ipcRenderer.invoke('attendance.summary', filters),
    create: (payload) => ipcRenderer.invoke('attendance.create', payload),
    update: (id, payload) => ipcRenderer.invoke('attendance.update', id, payload),
    delete: (id) => ipcRenderer.invoke('attendance.delete', id),
    importRows: (rows) => ipcRenderer.invoke('attendance.import', rows),
  },
  schedule: {
    list: (filters) => ipcRenderer.invoke('schedule.list', filters),
    create: (payload) => ipcRenderer.invoke('schedule.create', payload),
    update: (id, payload) => ipcRenderer.invoke('schedule.update', id, payload),
    delete: (id) => ipcRenderer.invoke('schedule.delete', id),
    assignments: (filters) => ipcRenderer.invoke('schedule.assignments', filters),
    assign: (payload) => ipcRenderer.invoke('schedule.assign', payload),
    unassign: (id) => ipcRenderer.invoke('schedule.unassign', id),
  },
  attendanceCorrection: {
    list: (filters) => ipcRenderer.invoke('attendanceCorrection.list', filters),
    create: (payload) => ipcRenderer.invoke('attendanceCorrection.create', payload),
    review: (id, payload) => ipcRenderer.invoke('attendanceCorrection.review', id, payload),
  },
  leaveType: {
    list: (filters) => ipcRenderer.invoke('leaveType.list', filters),
    create: (payload) => ipcRenderer.invoke('leaveType.create', payload),
    update: (id, payload) => ipcRenderer.invoke('leaveType.update', id, payload),
    delete: (id) => ipcRenderer.invoke('leaveType.delete', id),
  },
  leaveBalance: {
    list: (filters) => ipcRenderer.invoke('leaveBalance.list', filters),
    adjust: (payload) => ipcRenderer.invoke('leaveBalance.adjust', payload),
  },
  leaveRequest: {
    list: (filters) => ipcRenderer.invoke('leaveRequest.list', filters),
    get: (id) => ipcRenderer.invoke('leaveRequest.get', id),
    summary: (filters) => ipcRenderer.invoke('leaveRequest.summary', filters),
    create: (payload) => ipcRenderer.invoke('leaveRequest.create', payload),
    update: (id, payload) => ipcRenderer.invoke('leaveRequest.update', id, payload),
    review: (id, payload) => ipcRenderer.invoke('leaveRequest.review', id, payload),
    cancel: (id, payload) => ipcRenderer.invoke('leaveRequest.cancel', id, payload),
  },

  earningType: {
    list: (filters) => ipcRenderer.invoke('earningType.list', filters),
    get: (id) => ipcRenderer.invoke('earningType.get', id),
    create: (payload) => ipcRenderer.invoke('earningType.create', payload),
    update: (id, payload) => ipcRenderer.invoke('earningType.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('earningType.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('earningType.delete', id),
  },
  earningAssignment: {
    list: (filters) => ipcRenderer.invoke('earningAssignment.list', filters),
    get: (id) => ipcRenderer.invoke('earningAssignment.get', id),
    create: (payload) => ipcRenderer.invoke('earningAssignment.create', payload),
    update: (id, payload) => ipcRenderer.invoke('earningAssignment.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('earningAssignment.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('earningAssignment.delete', id),
  },
  earningTransaction: {
    list: (filters) => ipcRenderer.invoke('earningTransaction.list', filters),
    get: (id) => ipcRenderer.invoke('earningTransaction.get', id),
    summary: (filters) => ipcRenderer.invoke('earningTransaction.summary', filters),
    create: (payload) => ipcRenderer.invoke('earningTransaction.create', payload),
    update: (id, payload) => ipcRenderer.invoke('earningTransaction.update', id, payload),
    setStatus: (id, status) => ipcRenderer.invoke('earningTransaction.setStatus', id, status),
    delete: (id) => ipcRenderer.invoke('earningTransaction.delete', id),
  },

  deductionType: {
    list: (filters) => ipcRenderer.invoke('deductionType.list', filters),
    get: (id) => ipcRenderer.invoke('deductionType.get', id),
    create: (payload) => ipcRenderer.invoke('deductionType.create', payload),
    update: (id, payload) => ipcRenderer.invoke('deductionType.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('deductionType.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('deductionType.delete', id),
  },
  deductionAssignment: {
    list: (filters) => ipcRenderer.invoke('deductionAssignment.list', filters),
    get: (id) => ipcRenderer.invoke('deductionAssignment.get', id),
    create: (payload) => ipcRenderer.invoke('deductionAssignment.create', payload),
    update: (id, payload) => ipcRenderer.invoke('deductionAssignment.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('deductionAssignment.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('deductionAssignment.delete', id),
  },
  loan: {
    list: (filters) => ipcRenderer.invoke('loan.list', filters),
    get: (id) => ipcRenderer.invoke('loan.get', id),
    summary: (filters) => ipcRenderer.invoke('loan.summary', filters),
    create: (payload) => ipcRenderer.invoke('loan.create', payload),
    update: (id, payload) => ipcRenderer.invoke('loan.update', id, payload),
    setStatus: (id, status) => ipcRenderer.invoke('loan.setStatus', id, status),
    recordPayment: (id, payload) => ipcRenderer.invoke('loan.recordPayment', id, payload),
    delete: (id) => ipcRenderer.invoke('loan.delete', id),
  },
  deductionTransaction: {
    list: (filters) => ipcRenderer.invoke('deductionTransaction.list', filters),
    get: (id) => ipcRenderer.invoke('deductionTransaction.get', id),
    summary: (filters) => ipcRenderer.invoke('deductionTransaction.summary', filters),
    create: (payload) => ipcRenderer.invoke('deductionTransaction.create', payload),
    update: (id, payload) => ipcRenderer.invoke('deductionTransaction.update', id, payload),
    setStatus: (id, status) => ipcRenderer.invoke('deductionTransaction.setStatus', id, status),
    delete: (id) => ipcRenderer.invoke('deductionTransaction.delete', id),
  },

  contributionType: {
    list: (filters) => ipcRenderer.invoke('contributionType.list', filters),
    get: (id) => ipcRenderer.invoke('contributionType.get', id),
    create: (payload) => ipcRenderer.invoke('contributionType.create', payload),
    update: (id, payload) => ipcRenderer.invoke('contributionType.update', id, payload),
    setStatus: (id, active) => ipcRenderer.invoke('contributionType.setStatus', id, active),
    delete: (id) => ipcRenderer.invoke('contributionType.delete', id),
  },

  contributionTable: {
    list: (filters) => ipcRenderer.invoke('contributionTable.list', filters),
    get: (id) => ipcRenderer.invoke('contributionTable.get', id),
    create: (payload) => ipcRenderer.invoke('contributionTable.create', payload),
    update: (id, payload) => ipcRenderer.invoke('contributionTable.update', id, payload),
    setStatus: (id, status) => ipcRenderer.invoke('contributionTable.setStatus', id, status),
    replaceBrackets: (id, brackets) =>
      ipcRenderer.invoke('contributionTable.replaceBrackets', id, brackets),
    delete: (id) => ipcRenderer.invoke('contributionTable.delete', id),
  },

  contribution: {
    calculate: (payload) => ipcRenderer.invoke('contribution.calculate', payload),
  },

  contributionRecord: {
    list: (filters) => ipcRenderer.invoke('contributionRecord.list', filters),
    get: (id) => ipcRenderer.invoke('contributionRecord.get', id),
    summary: (filters) => ipcRenderer.invoke('contributionRecord.summary', filters),
    create: (payload) => ipcRenderer.invoke('contributionRecord.create', payload),
    setStatus: (id, status) => ipcRenderer.invoke('contributionRecord.setStatus', id, status),
    delete: (id) => ipcRenderer.invoke('contributionRecord.delete', id),
  },

  report: {
    options: () => ipcRenderer.invoke('report.options'),
    dashboard: (filters) => ipcRenderer.invoke('report.dashboard', filters),
    payrollRegister: (filters) => ipcRenderer.invoke('report.payrollRegister', filters),
    payrollSummary: (filters) => ipcRenderer.invoke('report.payrollSummary', filters),
    earnings: (filters) => ipcRenderer.invoke('report.earnings', filters),
    deductions: (filters) => ipcRenderer.invoke('report.deductions', filters),
    contributions: (filters) => ipcRenderer.invoke('report.contributions', filters),
    netPay: (filters) => ipcRenderer.invoke('report.netPay', filters),
    variance: (payload) => ipcRenderer.invoke('report.variance', payload),
    bankTransfer: (filters) => ipcRenderer.invoke('report.bankTransfer', filters),
    exportPdf: (suggestedName) => ipcRenderer.invoke('report.exportPdf', suggestedName),
  },

  payroll: {
    list: (filters) => ipcRenderer.invoke('payroll.list', filters),
    get: (id) => ipcRenderer.invoke('payroll.get', id),
    details: (id) => ipcRenderer.invoke('payroll.details', id),
    employeeResult: (periodId, employeeId) =>
      ipcRenderer.invoke('payroll.employeeResult', periodId, employeeId),
    createPeriod: (payload) => ipcRenderer.invoke('payroll.createPeriod', payload),
    updatePeriod: (id, payload) => ipcRenderer.invoke('payroll.updatePeriod', id, payload),
    deletePeriod: (id) => ipcRenderer.invoke('payroll.deletePeriod', id),
    calculate: (id, actor) => ipcRenderer.invoke('payroll.calculate', id, actor),
    approve: (id, actor) => ipcRenderer.invoke('payroll.approve', id, actor),
    finalize: (id, actor) => ipcRenderer.invoke('payroll.finalize', id, actor),
    lock: (id, actor) => ipcRenderer.invoke('payroll.lock', id, actor),
    cancel: (id, actor) => ipcRenderer.invoke('payroll.cancel', id, actor),
    register: (id) => ipcRenderer.invoke('payroll.register', id),
    employeeHistory: (filters) => ipcRenderer.invoke('payroll.employeeHistory', filters),
    run: (id) => ipcRenderer.invoke('payroll.run', id),
  },
});
